# Change these first
owner: Nilead # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: Nilead
    url: https://nilead.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.nilead.com
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Nilead Website and Services Status
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: You can check the current uptime status of our main website and services
  navbar:
    - title: Nilead Status Monitor
      href: /
    - title: Nilead
      href: https://nilead.com

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
