# Change these first
owner: Nilead # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: Nilead
    url: https://nilead.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.nilead.com
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/Nilead/uptime/master/assets/logo-black-icon.svg
  name: Nilead Website and Services Status
  introTitle: You can check the current uptime status of our main website and services
  introMessage: All issues are automatically notified to our system admins and will be fixed as soon as possible.
  navbar:
    - title: Nilead Status Monitor
      href: /
    - title: Nilead
      href: https://nilead.com

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
